name: Deploy to Render

on: 
  push:
      branches:
          - main

jobs:
  build-and-deploy:
      runs-on: ubuntu-latest

      steps:
          - name: Checkout the repo/code
            uses: actions/checkout@v2

          - name: Setup Docker Builder
            uses: docker/setup-buildx-action@v3
            
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          
          - name: Build and Push Docker Image
            uses: docker/build-push-action@v6
            with:
              context: .
              file: Dockerfile
              push: true
              tags: ${{ secrets.DOCKER_USERNAME }}/lesson8mongoose:latest
              build-args: MONGO_URI=${{ secrets.MONGO_URI }}
              
          - name: Deploy to Prod
            uses: johnbeynon/render-deploy-action@v0.0.8
            with:
              service-id: ${{ secrets.SERVICE_ID }}
              api-key: ${{ secrets.API_KEY }}
